/* Generated By:JavaCC: Do not edit this line. VizeParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface VizeParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TIMES = 5;
  /** RegularExpression Id. */
  int DIVIDE = 6;
  /** RegularExpression Id. */
  int POWER = 7;
  /** RegularExpression Id. */
  int LRP = 8;
  /** RegularExpression Id. */
  int RRP = 9;
  /** RegularExpression Id. */
  int RNUM = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"(\"",
    "\")\"",
    "<RNUM>",
    "\"x\"",
  };

}
